### ISSUE TITLE
Changing Settings

### ISSUE THREAD

**Issue by calimansi** [iprak/sensi#6]
Changing settings in home assistant doesn't stick... it reverts back to what it was, most of the time.  Do I need to do anything else to fix this?

Awesome project, by the way.

Thanks.

**Comment by iprak** [comment]
a) Are you logged into the Sensi app at the same time?
b) Do you see any errors logged in HomeAssistant ?

**Comment by calimansi** [comment]
I am seeing timeout errors in Home Assistant.  

I am logged in on the sensi app... that's a good point.  I'll log out now.

**Comment by calimansi** [comment]
More testing for you...

I can turn the fan on and off pretty reliably.  It's when I want to put it in circulate mode and then take it out.  Circulate mode will stick.

Also with the unit completely off, and I want to put in a new set point, the new set point will not stick.

**Comment by iprak** [comment]
Thanks for the testing.

Timeout error might be that the Sensi web end point is not responding for some reason,

I do myself sometimes see such warnings and then it will get resolved. Unfortunately, this component is built on reverse engineering so there definitely can be shortcomings. 

```
Timed out waiting for data
August 29, 2023 at 6:34:57 PM – (WARNING) Sensi (custom integration) - message first occurred at August 29, 2023 at 12:34:31 AM and shows up 4 times
```

Does the operation itself succeed, if you view the device status in the app ?

**Comment by calimansi** [comment]
It looks like it succeeds, then 30 to 60 seconds later, it changes back to what it was.

**Comment by calimansi** [comment]
Let me ask you this... can I adjust the setpoint with the unit being off?

Can I run circulate mode with the fan being in auto previously?

**Comment by iprak** [comment]
So HomeAssistant cards allow set point to be adjusted even if unit was off but the app does not.
Circulate is a special mode of "auto".

**Comment by calimansi** [comment]
So, if the fan is in auto, I can't go straight into circulate mode.  Can you on yours?

**Comment by calimansi** [comment]
It got warm enough here to turn on my AC.  Turning it on was no problem.  I then had to input the setpoint change (3) times for it to stick.  I am logged out of the sensi app.  There is a timeout issue in the logs:

Logger: custom_components.sensi.coordinator
Source: custom_components/sensi/coordinator.py:393

**Comment by iprak** [comment]
I am randomly seeing this problem as well. The server call succeeds but if the next data load is within 5-10 seconds then in brings in the previous value.  The next refresh seems to bring in the correct data. The refresh happens every 30 seconds.

Here was my sample workflow where I changed the cool_target to 85. My thermostat did update but the next refresh (5 second later) brought back older temperature. The next refresh (30 sec later) brought the correct temperature.


```
2023-09-02 20:48:32.697 INFO (MainThread) [custom_components.sensi] Set temperature to 85
2023-09-02 20:48:37.554 INFO (MainThread) [custom_components.sensi] Updating Test (36-6f-92-ff-fe-02-24-b7)
2023-09-02 20:48:37.555 INFO (MainThread) [custom_components.sensi] 73°F humidity=59 hvac_mode=cool fan_mode=auto hvac_action=None cool_target=83 heat_target=62
2023-09-02 20:49:08.499 INFO (MainThread) [custom_components.sensi] Updating Test (36-6f-92-ff-fe-02-24-b7)
2023-09-02 20:49:08.499 INFO (MainThread) [custom_components.sensi] 73°F humidity=60 hvac_mode=cool fan_mode=auto hvac_action=None cool_target=85 heat_target=62
```

Skipping the next data refresh, if it happens to be within the next 10 seconds seems to resolve the issue.  I will play more with this potential fix.

**Comment by calimansi** [comment]
So, I think something isn't quite right with circulate mode.  When I attempt to go into circulate mode, it will sometimes go into it and it sometimes won't.  When trying to get out of circulate mode (into either on or auto), it will not.  I need to stop it by logging back into the sensi app to stop circulate mode.

**Comment by calimansi** [comment]
Sorry... deleted my other comment... I wrote it before seeing your response.  I appreciate you looking at this.  Thanks.  I find it more dependable if I go through a browser on a computer versus on the phone, if that helps.

**Comment by iprak** [comment]
I have pushed out a new release, it might help with operations not taking place but no guarantees. I tested it with 2 thermostats and seems more reliable that before. My thermostat would go offline (no longer on wifi) leading to confusion. I did not see a way to flag this `offline` status in ui but did include an attribute for the same. Please note that this is a breaking release.

**Comment by calimansi** [comment]
Trying this out... so far so good.  I like the addition of battery status.

**Comment by calimansi** [comment]
I think this issue is still popping up for me every now and then.  Settings not sticking.

**Comment by nicolasjoly** [comment]
First of all, thanks for your integration! Would it be possible to "expose" the fan control? Currently I can click on Controls and modify Fan mode from Off/On/Circulate, but I can't seem to modify this in an Automation. In Automations I can see "Change HVAC mode on Sensi", but nothing for the fan mode.

**Comment by iprak** [comment]
I am closing this because the issue is stale. Please open a new one and include debug logging data.
